# Generated by Django 3.2.3 on 2021-05-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220)),
                ('url', models.URLField()),
                ('currentprice', models.FloatField(blank=True)),
                ('oldprice', models.FloatField(default=0)),
                ('pricedifference', models.FloatField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('pricedifference', '-created'),
            },
        ),
    ]
